import { z } from "zod";

export const onboardingCompleteSchema = z.object({
  dateOfBirth: z.string().optional(),
  bio: z.string().max(500).optional(),
  phone: z.string().min(1).max(20).optional(),
  department: z.string().max(100).optional(),
  designation: z.string().max(100).optional(),
  skills: z.string().max(1000).optional(),
  linkedinUrl: z.string().url().max(500).optional().or(z.literal("")),
  secretQuestion: z.string().min(1, "Secret question is required"),
  secretAnswer: z.string().min(1, "Secret answer is required").max(200),
  address: z.string().max(500).optional(),
  city: z.string().max(100).optional(),
  state: z.string().max(100).optional(),
  country: z.string().max(100).optional(),
  pincode: z.string().max(20).optional(),
  alternateEmail: z.string().email().optional().or(z.literal("")),
  about: z.string().max(2000).optional(),
  twitterUrl: z.string().url().max(500).optional().or(z.literal("")),
  githubUrl: z.string().url().max(500).optional().or(z.literal("")),
  instagramUrl: z.string().url().max(500).optional().or(z.literal("")),
  websiteUrl: z.string().url().max(500).optional().or(z.literal("")),
});

export const onboardingSaveProgressSchema = z.object({
  step: z.number().int().min(0).max(3),
  dateOfBirth: z.string().optional(),
  bio: z.string().max(500).optional(),
  phone: z.string().max(20).optional(),
  department: z.string().max(100).optional(),
  designation: z.string().max(100).optional(),
  skills: z.string().max(1000).optional(),
  linkedinUrl: z.string().max(500).optional(),
  secretQuestion: z.string().max(200).optional(),
  secretAnswer: z.string().max(200).optional(),
  address: z.string().max(500).optional(),
  city: z.string().max(100).optional(),
  state: z.string().max(100).optional(),
  country: z.string().max(100).optional(),
  pincode: z.string().max(20).optional(),
  alternateEmail: z.string().max(200).optional(),
  about: z.string().max(2000).optional(),
  twitterUrl: z.string().max(500).optional(),
  githubUrl: z.string().max(500).optional(),
  instagramUrl: z.string().max(500).optional(),
  websiteUrl: z.string().max(500).optional(),
});
