import { useState, useEffect, useCallback } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { useParams, useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import { DragDropContext, Droppable, Draggable } from '@hello-pangea/dnd';
import { ArrowLeft, Plus, Calendar, Users, CheckCircle2, Clock, AlertCircle, Edit3, Trash2, ListTodo, FileText, Target, User, Flag, BarChart3 } from 'lucide-react';
import { projectsApi, tasksApi, teamApi } from '../services/api';

const STATUS_COLORS = { PLANNING: '#e3e7ed', ACTIVE: '#cce5ff', IN_REVIEW: '#fff3cd', COMPLETED: '#d4edda', ON_HOLD: '#f8d7da' };
const STATUS_TEXT_COLORS = { PLANNING: '#596882', ACTIVE: '#004085', IN_REVIEW: '#856404', COMPLETED: '#155724', ON_HOLD: '#721c24' };
const PRIORITY_COLORS = { LOW: { bg: 'bg-gray-500/10', color: 'text-gray-400' }, MEDIUM: { bg: 'bg-blue-500/10', color: 'text-blue-400' }, HIGH: { bg: 'bg-amber-500/10', color: 'text-amber-400' }, URGENT: { bg: 'bg-red-500/10', color: 'text-red-400' } };
const KANBAN_COLUMNS = [{ id: 'TODO', title: 'Todo', color: '#e3e7ed', textColor: '#596882' },{ id: 'IN_PROGRESS', title: 'In Progress', color: '#cce5ff', textColor: '#004085' },{ id: 'IN_REVIEW', title: 'In Review', color: '#fff3cd', textColor: '#856404' },{ id: 'COMPLETED', title: 'Completed', color: '#d4edda', textColor: '#155724' }];
const AVATAR_COLORS = ['#7C3AED', '#8B3FE9', '#16A34A', '#EA580C', '#CB3939', '#2563EB', '#059669', '#D97706', '#DC2626', '#111827'];
function getInitials(name) { if (!name) return '??'; return name.split(' ').map(w => w[0]).join('').toUpperCase().slice(0, 2); }
function getAvatarColor(name) { if (!name) return AVATAR_COLORS[0]; let hash = 0; for (let i = 0; i < name.length; i++) hash = name.charCodeAt(i) + ((hash << 5) - hash); return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length]; }
function formatDate(dateStr) { if (!dateStr) return '--'; return new Date(dateStr).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); }
const inputClass = 'w-full bg-[var(--bg-elevated)] border border-[var(--border-default)] rounded-lg px-3 py-2 text-[var(--text-primary)] placeholder:text-[var(--text-muted)] focus:border-[#7C3AED] focus:ring-2 focus:ring-[#7C3AED]/20 outline-none text-[13px]';
const labelClass = 'block text-[11px] font-semibold text-[var(--text-muted)] uppercase tracking-wide mb-1.5';

export default function ProjectDetail() {
  const { id } = useParams(); const dispatch = useDispatch(); const navigate = useNavigate();
  const [project, setProject] = useState(null); const [tasks, setTasks] = useState([]); const [teamMembers, setTeamMembers] = useState([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const [activeTab, setActiveTab] = useState('overview');
  const [showAddTask, setShowAddTask] = useState(false); const [creatingTask, setCreatingTask] = useState(false);
  const [taskForm, setTaskForm] = useState({ title: '', description: '', assignee_id: '', priority: 'MEDIUM', status: 'TODO', due_date: '' });

  useEffect(() => { dispatch({ type: 'UI_SET_PAGE_TITLE', payload: project?.name || 'Project Detail' }); }, [dispatch, project?.name]);
  useEffect(() => { setProject(null); setTasks([]); setActiveTab('overview'); setLoading(true); }, [id]);

  const fetchProject = useCallback(async () => {
    try { setLoading(true); setError(null); const res = await projectsApi.get(id); let data = res.data; if (Array.isArray(data)) data = data[0]; if (data?.project) data = data.project;
      setProject(data); if (data?.name) dispatch({ type: 'UI_SET_PAGE_TITLE', payload: data.name }); if (data?.tasks?.length > 0) setTasks(data.tasks);
    } catch (err) { setError(err.response?.data?.message || 'Failed to load project'); toast.error('Failed to load project'); } finally { setLoading(false); }
  }, [id]);
  const fetchTasks = useCallback(async () => { try { const res = await tasksApi.list({ projectId: id }); setTasks(Array.isArray(res.data) ? res.data : res.data?.tasks || []); } catch {} }, [id]);
  const fetchTeam = useCallback(async () => { try { const res = await teamApi.list(); setTeamMembers(Array.isArray(res.data) ? res.data : res.data?.members || []); } catch {} }, []);
  useEffect(() => { fetchProject(); fetchTasks(); fetchTeam(); }, [fetchProject, fetchTasks, fetchTeam]);

  const handleAddTask = async (e) => { e.preventDefault(); if (!taskForm.title.trim()) { toast.warning('Task title is required'); return; }
    try { setCreatingTask(true); await tasksApi.create({ title: taskForm.title, description: taskForm.description, assigneeId: taskForm.assignee_id || undefined, priority: taskForm.priority, status: taskForm.status, dueDate: taskForm.due_date || undefined, projectId: id });
      toast.success('Task created'); setShowAddTask(false); setTaskForm({ title: '', description: '', assignee_id: '', priority: 'MEDIUM', status: 'TODO', due_date: '' }); fetchTasks();
    } catch (err) { toast.error(err.response?.data?.message || 'Failed to create task'); } finally { setCreatingTask(false); } };

  const handleDragEnd = async (result) => { const { draggableId, destination, source } = result; if (!destination || (destination.droppableId === source.droppableId && destination.index === source.index)) return;
    setTasks(prev => prev.map(t => t.id?.toString() === draggableId ? { ...t, status: destination.droppableId } : t));
    try { await tasksApi.update(draggableId, { status: destination.droppableId }); } catch { toast.error('Failed to update task status'); fetchTasks(); } };

  const kanbanData = {}; KANBAN_COLUMNS.forEach(col => { kanbanData[col.id] = tasks.filter(t => t.status === col.id); });
  const totalTasks = tasks.length; const completedTasks = tasks.filter(t => t.status === 'COMPLETED').length;
  const inProgressTasks = tasks.filter(t => t.status === 'IN_PROGRESS').length;
  const progress = project?.progress || (totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0);

  if (loading) return <div className="flex items-center justify-center py-20"><div className="w-6 h-6 border-2 border-[#7C3AED] border-t-transparent rounded-full animate-spin" /></div>;
  if (error || !project) return (<div><button className="bg-transparent border border-[var(--border-default)] text-[var(--text-secondary)] rounded-lg px-3 py-1.5 text-[12px] font-semibold hover:bg-[var(--bg-elevated)] transition-colors flex items-center gap-1 mb-4" onClick={() => navigate('/projects')}><ArrowLeft size={16} /> Back</button><div className="bg-[var(--bg-card)] border border-[var(--border-default)] rounded-xl flex flex-col items-center py-16 gap-3"><AlertCircle size={48} className="text-red-400" /><p className="text-red-400">{error || 'Project not found'}</p><button className="bg-transparent border border-[var(--border-default)] text-[var(--text-secondary)] rounded-lg px-4 py-2 text-[13px] font-semibold" onClick={fetchProject}>Try Again</button></div></div>);

  const projectTeam = project.members || project.team || [];
  return (
    <div>
      <div className="mb-6">
        <button className="bg-transparent border border-[var(--border-default)] text-[var(--text-secondary)] rounded-lg px-3 py-1.5 text-[12px] font-semibold hover:bg-[var(--bg-elevated)] transition-colors flex items-center gap-1 mb-4" onClick={() => navigate('/projects')} data-testid="back-btn"><ArrowLeft size={16} /> Back to Projects</button>
        <div className="flex items-start justify-between flex-wrap gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2"><h1 className="text-[24px] font-bold text-[var(--text-primary)] font-[Manrope]">{project.name}</h1><span className="text-[11px] px-2 py-0.5 rounded-full font-semibold" style={{ background: STATUS_COLORS[project.status] || '#e3e7ed', color: STATUS_TEXT_COLORS[project.status] || '#596882' }}>{(project.status || 'PLANNING').replace(/_/g, ' ')}</span></div>
            <div className="flex gap-4 text-[13px] text-[var(--text-muted)] flex-wrap"><span className="flex items-center gap-1"><Calendar size={14} /> Due: {formatDate(project.dueDate || project.due_date)}</span><span className="flex items-center gap-1"><User size={14} /> Lead: {project.manager ? `${project.manager.firstName} ${project.manager.lastName}` : '--'}</span><span className="flex items-center gap-1"><BarChart3 size={14} /> {progress}% complete</span></div>
          </div>
          <button className="bg-[#7C3AED] text-white rounded-lg px-4 py-2 text-[13px] font-semibold hover:bg-[#7C3AED]/90 transition-colors flex items-center gap-1" onClick={() => setShowAddTask(true)} data-testid="add-task"><Plus size={16} /> Add Task</button>
        </div>
        <div className="mt-4 h-2 bg-[var(--border-default)] rounded-full overflow-hidden"><div className="h-full rounded-full transition-all duration-300" style={{ width: `${progress}%`, background: progress >= 100 ? '#16A34A' : '#7C3AED' }} /></div>
      </div>

      <div className="bg-[var(--bg-card)] border border-[var(--border-default)] rounded-xl mb-6"><div className="px-5 border-b border-[var(--border-default)]"><nav className="flex">{[{ key: 'overview', label: 'Overview', icon: <FileText size={15} /> },{ key: 'tasks', label: 'Tasks', icon: <ListTodo size={15} /> },{ key: 'team', label: 'Team', icon: <Users size={15} /> }].map(tab => (<button key={tab.key} onClick={() => setActiveTab(tab.key)} className={`flex items-center gap-1.5 px-4 py-3.5 text-[13px] font-semibold border-b-2 transition-colors ${activeTab === tab.key ? 'text-[#7C3AED] border-[#7C3AED]' : 'text-[var(--text-muted)] border-transparent'}`} data-testid={`tab-${tab.key}`}>{tab.icon} {tab.label}</button>))}</nav></div></div>

      {activeTab === 'overview' && (<div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-4">{[{ label: 'Total Tasks', value: totalTasks },{ label: 'Completed', value: completedTasks, color: 'text-green-400' },{ label: 'In Progress', value: inProgressTasks, color: 'text-[#7C3AED]' },{ label: 'Todo', value: tasks.filter(t => t.status === 'TODO').length, color: 'text-amber-400' }].map((s, i) => (<div key={i} className="bg-[var(--bg-card)] border border-[var(--border-default)] rounded-xl p-4"><div className={`text-[22px] font-bold ${s.color || 'text-[var(--text-primary)]'}`}>{s.value}</div><div className="text-[12px] text-[var(--text-muted)]">{s.label}</div></div>))}</div><div className="bg-[var(--bg-card)] border border-[var(--border-default)] rounded-xl overflow-hidden"><div className="px-4 py-3 border-b border-[var(--border-default)]"><h6 className="text-[14px] font-semibold text-[var(--text-primary)]">Description</h6></div><div className="p-4"><p className="text-[14px] leading-relaxed text-[var(--text-secondary)]">{project.description || 'No description provided.'}</p></div></div></div>)}

      {activeTab === 'tasks' && (<DragDropContext onDragEnd={handleDragEnd}><div className="flex gap-4 overflow-x-auto pb-4">{KANBAN_COLUMNS.map(column => (<div key={column.id} className="flex-1 min-w-[260px] bg-[var(--bg-elevated)] rounded-xl flex flex-col"><div className="px-4 py-3 flex items-center gap-2" style={{ borderBottom: `2px solid ${column.color}` }}><span className="w-2 h-2 rounded-full" style={{ background: column.textColor }} /><span className="text-[13px] font-bold text-[var(--text-primary)]">{column.title}</span><span className="text-[11px] font-bold text-[var(--text-muted)] bg-[var(--border-default)] px-2 py-0.5 rounded-full">{kanbanData[column.id]?.length || 0}</span></div><Droppable droppableId={column.id}>{(provided, snapshot) => (<div ref={provided.innerRef} {...provided.droppableProps} className={`p-2 flex-1 min-h-[120px] ${snapshot.isDraggingOver ? 'bg-[#7C3AED]/5' : ''}`}>{kanbanData[column.id]?.map((task, index) => (<Draggable key={task.id?.toString()} draggableId={task.id?.toString()} index={index}>{(prov, snap) => (<div ref={prov.innerRef} {...prov.draggableProps} {...prov.dragHandleProps} className={`mb-2 bg-[var(--bg-card)] border border-[var(--border-default)] rounded-lg p-3 ${snap.isDragging ? 'shadow-lg' : ''}`} style={prov.draggableProps.style} data-testid="task-card"><div className="text-[13px] font-semibold text-[var(--text-primary)] mb-1">{task.title}</div>{task.priority && <span className={`text-[10px] px-2 py-0.5 rounded-full font-semibold inline-flex items-center gap-1 ${(PRIORITY_COLORS[task.priority] || PRIORITY_COLORS.MEDIUM).bg} ${(PRIORITY_COLORS[task.priority] || PRIORITY_COLORS.MEDIUM).color}`}><Flag size={10} />{task.priority}</span>}</div>)}</Draggable>))}{provided.placeholder}{(!kanbanData[column.id] || kanbanData[column.id].length === 0) && <div className="text-center py-5 text-[var(--text-muted)] text-[12px]">No tasks</div>}</div>)}</Droppable></div>))}</div></DragDropContext>)}

      {activeTab === 'team' && (<div>{projectTeam.length > 0 ? (<div className="grid grid-cols-2 md:grid-cols-4 gap-3">{projectTeam.map((m, i) => (<div key={m.id || i} className="bg-[var(--bg-card)] border border-[var(--border-default)] rounded-xl text-center p-6"><div className="w-12 h-12 rounded-full mx-auto mb-3 flex items-center justify-center text-white font-bold" style={{ background: getAvatarColor(m.name || m.full_name || 'U') }}>{getInitials(m.name || m.full_name || 'U')}</div><h6 className="text-[14px] font-semibold text-[var(--text-primary)]">{m.name || m.full_name || 'Unknown'}</h6><p className="text-[12px] text-[var(--text-muted)]">{m.role || 'Team Member'}</p></div>))}</div>) : <div className="bg-[var(--bg-card)] border border-[var(--border-default)] rounded-xl flex flex-col items-center py-16 gap-2"><Users size={40} className="text-[var(--text-muted)]" /><p className="text-[var(--text-muted)]">No team members assigned</p></div>}</div>)}

      {showAddTask && (<div className="fixed inset-0 z-[2000] flex items-center justify-center"><div className="absolute inset-0 bg-[var(--bg-primary)]/80" onClick={() => setShowAddTask(false)} /><div className="relative bg-[var(--bg-card)] border border-[var(--border-default)] rounded-xl w-[720px] max-w-[95vw] shadow-2xl"><form onSubmit={handleAddTask}><div className="px-5 py-4 border-b border-[var(--border-default)]"><h5 className="text-[18px] font-bold text-[var(--text-primary)]">Add Task</h5></div><div className="p-5 grid gap-3"><div><label className={labelClass}>Title *</label><input className={inputClass} placeholder="Task title" value={taskForm.title} onChange={e => setTaskForm({ ...taskForm, title: e.target.value })} required data-testid="task-title" /></div><div><label className={labelClass}>Description</label><textarea className={`${inputClass} resize-y`} rows={3} value={taskForm.description} onChange={e => setTaskForm({ ...taskForm, description: e.target.value })} /></div><div className="grid grid-cols-2 gap-3"><div><label className={labelClass}>Assignee</label><select className={inputClass} value={taskForm.assignee_id} onChange={e => setTaskForm({ ...taskForm, assignee_id: e.target.value })}><option value="">Unassigned</option>{teamMembers.map(m => <option key={m.id} value={m.id}>{m.name || m.email}</option>)}</select></div><div><label className={labelClass}>Priority</label><select className={inputClass} value={taskForm.priority} onChange={e => setTaskForm({ ...taskForm, priority: e.target.value })}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></div></div><div className="grid grid-cols-2 gap-3"><div><label className={labelClass}>Status</label><select className={inputClass} value={taskForm.status} onChange={e => setTaskForm({ ...taskForm, status: e.target.value })}><option value="TODO">Todo</option><option value="IN_PROGRESS">In Progress</option><option value="IN_REVIEW">In Review</option><option value="COMPLETED">Completed</option></select></div><div><label className={labelClass}>Due Date</label><input type="date" className={inputClass} value={taskForm.due_date} onChange={e => setTaskForm({ ...taskForm, due_date: e.target.value })} /></div></div></div><div className="px-5 py-3 border-t border-[var(--border-default)] flex justify-end gap-2"><button type="button" className="bg-transparent border border-[var(--border-default)] text-[var(--text-secondary)] rounded-lg px-4 py-2 text-[13px] font-semibold" onClick={() => setShowAddTask(false)}>Cancel</button><button type="submit" className="bg-[#7C3AED] text-white rounded-lg px-4 py-2 text-[13px] font-semibold disabled:opacity-50 flex items-center gap-1" disabled={creatingTask}>{creatingTask ? 'Creating...' : 'Add Task'}</button></div></form></div></div>)}
    </div>
  );
}
